In [1]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
X_LE = LabelEncoder()
Y_LE = LabelEncoder()
SS = StandardScaler()

import warnings
warnings.filterwarnings("ignore")


In [2]:
df = pd.read_csv("investing_program_prediction_data.csv")
df.head()

SE1  SE2  BA1  BA2    BA3      BA4      BA5     BA6    BA7 PE1  ... PE10  \
0   45  G29   12  0.0   5934        0        0       0      0  I0  ...   I0   
1   41   G0    0  0.0  21514   316374     5142       0   5141  I0  ...   I0   
2   43   G0    1  0.0  14324    22344    22344       0  22344  I0  ...   I0   
3   36  G52   16  0.0  41114  2406838  1156219  692875  41425  I0  ...   I1   
4    2  G10    0  0.0   2394      621      621       0    621  I0  ...   I0   

  PE11 PE12 PE13 PE14 PE15 IA1 IA2 IA3 InvType  
0   I0   I0   I0   I0   I0   0   0   1      C1  
1   I0   I1   I1   I1   I0   0   0   1      C1  
2   I0   I0   I0   I0   I0   0   0   0      C1  
3   I1   I1   I1   I0   I0   0   0   0      C1  
4   I0   I0   I0   I0   I0   0   0   0      C1  

[5 rows x 28 columns]

In [3]:
for column in ['PE' + str(i) for i in range(1,16)]:
    df[column] = df[column].apply(lambda x:x[1]).astype(np.int)

In [4]:
df

SE1  SE2  BA1  BA2    BA3      BA4      BA5      BA6     BA7  PE1  ...  \
0      45  G29   12  0.0   5934        0        0        0       0    0  ...   
1      41   G0    0  0.0  21514   316374     5142        0    5141    0  ...   
2      43   G0    1  0.0  14324    22344    22344        0   22344    0  ...   
3      36  G52   16  0.0  41114  2406838  1156219   692875   41425    0  ...   
4       2  G10    0  0.0   2394      621      621        0     621    0  ...   
...   ...  ...  ...  ...    ...      ...      ...      ...     ...  ...  ...   
4729   57  G23    1  0.0  12514    14274    14274        0   14274    0  ...   
4730   34  G66    0  0.0   5994     1036     1036        0    1036    0  ...   
4731   44  G51   19  0.0  69627  4805913  3345950  1899126  596537    0  ...   
4732   22   G0    0  0.0   5999        0        0        0       0    0  ...   
4733   47  G67    0  0.0  23531    16786    16786        0   16786    0  ...   

      PE10  PE11  PE12  PE13  PE14  PE15  IA1  IA2  IA3  InvType  
0        0     0     0     0     0     0    0    0    1       C1  
1        0     0     1     1     1     0    0    0    1       C1  
2        0     0     0     0     0     0    0    0    0       C1  
3        1     1     1     1     0     0    0    0    0       C1  
4        0     0     0     0     0     0    0    0    0       C1  
...    ...   ...   ...   ...   ...   ...  ...  ...  ...      ...  
4729     0     0     0     0     0     0    0    0    0       C0  
4730     0     0     0     0     0     0    0    0    0       C1  
4731     1     1     1     1     1     0    0    0    1       C1  
4732     0     0     0     0     0     0    0    0    0       C1  
4733     0     0     0     0     0     0    0    0    0       C0  

[4734 rows x 28 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4734 entries, 0 to 4733
Data columns (total 28 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   SE1      4734 non-null   int64  
 1   SE2      4734 non-null   object 
 2   BA1      4734 non-null   int64  
 3   BA2      4734 non-null   float64
 4   BA3      4734 non-null   int64  
 5   BA4      4734 non-null   int64  
 6   BA5      4734 non-null   int64  
 7   BA6      4734 non-null   int64  
 8   BA7      4734 non-null   int64  
 9   PE1      4734 non-null   int32  
 10  PE2      4734 non-null   int32  
 11  PE3      4734 non-null   int32  
 12  PE4      4734 non-null   int32  
 13  PE5      4734 non-null   int32  
 14  PE6      4734 non-null   int32  
 15  PE7      4734 non-null   int32  
 16  PE8      4734 non-null   int32  
 17  PE9      4734 non-null   int32  
 18  PE10     4734 non-null   int32  
 19  PE11     4734 non-null   int32  
 20  PE12     4734 non-null   int32  
 21  PE13     4734 

In [6]:
X = df.drop("InvType",axis=1)
X['SE2'] = X_LE.fit_transform(X['SE2'])
X = SS.fit_transform(X)
X

array([[ 0.09809128, -0.45740755,  0.95579582, ..., -0.02941807,
        -0.01453556,  0.68946272],
       [-0.15758064, -1.18067764, -0.64914784, ..., -0.02941807,
        -0.01453556,  0.68946272],
       [-0.02974468, -1.18067764, -0.51540253, ..., -0.02941807,
        -0.01453556, -0.51404632],
       ...,
       [ 0.0341733 ,  0.26586254,  1.89201295, ..., -0.02941807,
        -0.01453556,  0.68946272],
       [-1.37202224, -1.18067764, -0.64914784, ..., -0.02941807,
        -0.01453556, -0.51404632],
       [ 0.22592724,  0.78248404, -0.64914784, ..., -0.02941807,
        -0.01453556, -0.51404632]])

In [7]:
df.InvType.value_counts()

C1    2416
C0    2318
Name: InvType, dtype: int64

In [8]:
Y = Y_LE.fit_transform(df.InvType)
Y

array([1, 1, 1, ..., 1, 1, 0])

In [9]:
Y_LE.inverse_transform([0])

array(['C0'], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=1)

In [11]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

In [12]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79       705
           1       0.80      0.78      0.79       716

    accuracy                           0.79      1421
   macro avg       0.79      0.79      0.79      1421
weighted avg       0.79      0.79      0.79      1421



In [13]:
pickle.dump(X_LE, open("X_LE.pkl",'wb'))
pickle.dump(Y_LE, open("Y_LE.pkl",'wb'))
pickle.dump(SS, open("SS.pkl",'wb'))

pickle.dump(model, open("GBC_model.pkl",'wb'))

In [14]:
df.sample(1).values


array([[72, 'G26', 0, 0.0, 116327, 129864, 129864, 0, 129864, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 'C1']], dtype=object)